.TH "LIGHTNING-PING" "7" "" "" "lightning-ping"
.SH NAME
lightning-ping - Command to check if a node is up\.
.SH SYNOPSIS

\fBping\fR \fIid\fR [\fIlen\fR] [\fIpongbytes\fR]

.SH DESCRIPTION

The \fBping\fR command checks if the node with \fIid\fR is ready to talk\. 
It currently only works for peers we have a channel with\.


It accepts the following parameters:


.RS
.IP \[bu]
\fIid\fR: A string that represents the node id;
.IP \[bu]
\fIlen\fR: A integer that represents the length of the ping (default 128);
.IP \[bu]
\fIpongbytes\fR: An integer that represents the length of the reply (default 128)\.
A value of 65532 to 65535 means "don't reply"\.

.RE
.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "ping",
  "params": {
    "len": 128,
    "pongbytes": 128
  }
}
.RE

.fi
.SH RETURN VALUE

On success, an object is returned, containing:


.RS
.IP \[bu]
\fBtotlen\fR (u16): the answer length of the reply message (including header: 0 means no reply expected)

.RE

On failure, one of the following error codes may be returned:


.RS
.IP \[bu]
-32602: Error in given parameters or we're already waiting for a ping response from peer\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
   "totlen": 132
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page, but many others did the hard work of actually implementing this rpc command\.

.SH SEE ALSO

\fBlightning-connect\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:ebe174284ad5fda257dda17c3b9f81fe5dcd4072ab06bb72fa3e1b2d7629c2d3
